export const BOROUGHS = [
    { value: "Côte-des-Neiges–Notre-Dame-de-Grâce", label: "Côte-des-Neiges–Notre-Dame-de-Grâce" },
    { value: "Ville-Marie", label: "Ville-Marie" },
    { value: "Ahuntsic-Cartierville", label: "Ahuntsic-Cartierville" },
    { value: "Villeray–Saint-Michel–Parc-Extension", label: "Villeray–Saint-Michel–Parc-Extension" },
    { value: "Rosemont–La Petite-Patrie", label: "Rosemont–La Petite-Patrie" },
    { value: "Mercier–Hochelaga-Maisonneuve", label: "Mercier–Hochelaga-Maisonneuve" },
    { value: "Rivière-des-Prairies–Pointe-aux-Trembles", label: "Rivière-des-Prairies–Pointe-aux-Trembles" },
    { value: "Le Sud-Ouest", label: "Le Sud-Ouest" },
    { value: "Saint-Laurent", label: "Saint-Laurent" },
    { value: "Pierrefonds-Roxboro", label: "Pierrefonds-Roxboro" },
    { value: "Anjou", label: "Anjou" },
    { value: "L'Île-Bizard–Sainte-Geneviève", label: "L'Île-Bizard–Sainte-Geneviève" },
    { value: "Montréal-Nord", label: "Montréal-Nord" },
    { value: "Outremont", label: "Outremont" },
    { value: "Sainte-Anne-de-Bellevue", label: "Sainte-Anne-de-Bellevue" },
    { value: "Verdun", label: "Verdun" },
    { value: "Westmount", label: "Westmount" },
    { value: "Île-Dorval", label: "Île-Dorval" },
    { value: "Rivière-des-Prairies–Pointe-aux-Trembles", label: "Rivière-des-Prairies–Pointe-aux-Trembles" },
    { value: "Ahuntsic-Cartierville", label: "Ahuntsic-Cartierville" },
    { value: "Anjou", label: "Anjou" },
    { value: "Verdun", label: "Verdun" },
    { value: "Côte-des-Neiges–Notre-Dame-de-Grâce", label: "Côte-des-Neiges–Notre-Dame-de-Grâce" },
    { value: "Pierrefonds-Roxboro", label: "Pierrefonds-Roxboro" },
    { value: "Mercier–Hochelaga-Maisonneuve", label: "Mercier–Hochelaga-Maisonneuve" },
    { value: "Ville-Marie", label: "Ville-Marie" },
    { value: "Le Sud-Ouest", label: "Le Sud-Ouest" },
    { value: "Saint-Laurent", label: "Saint-Laurent" },
    { value: "Rosemont–La Petite-Patrie", label: "Rosemont–La Petite-Patrie" },
    { value: "Outremont", label: "Outremont" },
    { value: "Sainte-Anne-de-Bellevue", label: "Sainte-Anne-de-Bellevue" },
    { value: "Villeray–Saint-Michel–Parc-Extension", label: "Villeray–Saint-Michel–Parc-Extension" },
    { value: "Montréal-Nord", label: "Montréal-Nord" },
    { value: "L'Île-Bizard–Sainte-Geneviève", label: "L'Île-Bizard–Sainte-Geneviève" },
  ]