export const CITIES = [
    // { value: "Quebec", label: "Quebec" },
    // { value: "Saguenay", label: "Saguenay" },
    // { value: "Saint-Sauveur", label: "Saint-Sauveur" },
    // { value: "Bonaventure", label: "Bonaventure" },
    // { value: "Bois-des-Filion", label: "Bois-des-Filion" },
    // { value: "Saint-Basile-le-Grand", label: "Saint-Basile-le-Grand" },
    // { value: "Dollard-des-Ormeaux", label: "Dollard-des-Ormeaux" },
    // {
    //   value: "Notre-Dame-de-l'Île-Perrot",
    //   label: "Notre-Dame-de-l'Île-Perrot",
    // },
    // {
    //   value: "Notre-Dame-de-l'Île-Perrot",
    //   label: "Notre-Dame-de-l'Île-Perrot",
    // },
    // { value: "Val-Morin", label: "Val-Morin" },
    // { value: "Albanel", label: "Albanel" },
    // { value: "Berthierville", label: "Berthierville" },
    // { value: "Coteau-du-Lac", label: "Coteau-du-Lac" },
    // { value: "Victoriaville", label: "Victoriaville" },
    // { value: "Varennes", label: "Varennes" },
    // { value: "Saint-Lin-Laurentides", label: "Saint-Lin-Laurentides" },
    // { value: "Batiscan", label: "Batiscan" },


  //   { value: 'Danville', label: 'Danville' },
  //   { value: 'Saguenay', label: 'Saguenay' },
  //   { value: 'Saint-Sauveur', label: 'Saint-Sauveur' },
  //   { value: 'Bonaventure', label: 'Bonaventure' },
  //   { value: 'Bois-des-Filion', label: 'Bois-des-Filion' },
  //   { value: 'Saint-Basile-le-Grand', label: 'Saint-Basile-le-Grand' },
  //   { value: 'Dollard-des-Ormeaux', label: 'Dollard-des-Ormeaux' },
  //   {
  //     value: "Notre-Dame-de-l'Île-Perrot",
  //     label: "Notre-Dame-de-l'Île-Perrot"
  //   },
  //   { value: 'Val-Morin', label: 'Val-Morin' },
  //   { value: 'Albanel', label: 'Albanel' },
  //   { value: 'Berthierville', label: 'Berthierville' },
  //   { value: 'Coteau-du-Lac', label: 'Coteau-du-Lac' },
  //   { value: 'Victoriaville', label: 'Victoriaville' },
  //   { value: 'Varennes', label: 'Varennes' },
  //   { value: 'Saint-Lin-Laurentides', label: 'Saint-Lin-Laurentides' },
  //   { value: 'Batiscan', label: 'Batiscan' },
  //   { value: 'Cabano', label: 'Cabano' },
  //   { value: 'Saint-Eustache', label: 'Saint-Eustache' },
  //   { value: 'Sainte-Sophie', label: 'Sainte-Sophie' },
  //   { value: 'Bégin', label: 'Bégin' },
  //   { value: 'Biencourt', label: 'Biencourt' },
  //   { value: 'Brome', label: 'Brome' },
  //   { value: 'Côte-Saint-Luc', label: 'Côte-Saint-Luc' },
  //   { value: 'Terrebonne', label: 'Terrebonne' },
  //   {
  //     value: 'Saint-Jean-sur-Richelieu',
  //     label: 'Saint-Jean-sur-Richelieu'
  //   },
  //   { value: 'Blanc-Sablon', label: 'Blanc-Sablon' },
  //   { value: 'Granby', label: 'Granby' },
  //   { value: 'Sherbrooke', label: 'Sherbrooke' },
  //   { value: 'Béthanie', label: 'Béthanie' },
  //   { value: 'Lorraine', label: 'Lorraine' },
  //   {
  //     value: 'Sainte-Anne-des-Plaines',
  //     label: 'Sainte-Anne-des-Plaines'
  //   },
  //   { value: 'Dolbeau-Mistassini', label: 'Dolbeau-Mistassini' },
  //   { value: 'Rigaud', label: 'Rigaud' },
  //   { value: 'Montreal', label: 'Montreal' },
  //   { value: 'Longueuil', label: 'Longueuil' },
  //   { value: 'Joliette', label: 'Joliette' },
  //   { value: 'Mount Royal', label: 'Mount Royal' },
  //   { value: 'Bedford', label: 'Bedford' },
  //   { value: 'Saint-Hyacinthe', label: 'Saint-Hyacinthe' },
  //   { value: 'Amos', label: 'Amos' },
  //   { value: 'Coaticook', label: 'Coaticook' },
  //   { value: 'Baie-Saint-Paul', label: 'Baie-Saint-Paul' },
  //   { value: 'Sainte-Thérèse', label: 'Sainte-Thérèse' },
  //   { value: 'Carleton-sur-Mer', label: 'Carleton-sur-Mer' },
  //   { value: "Val-d'Or", label: "Val-d'Or" },
  //   { value: 'Rosemère', label: 'Rosemère' },
  //   { value: 'Château-Richer', label: 'Château-Richer' },
  //   { value: 'Beauharnois', label: 'Beauharnois' },
  //   { value: 'Gatineau', label: 'Gatineau' },
  //   { value: 'Beaumont', label: 'Beaumont' },
  //   { value: 'Bryson', label: 'Bryson' },
  //   { value: 'Cap-Santé', label: 'Cap-Santé' },
  //   { value: 'Shawinigan', label: 'Shawinigan' },
  //   { value: 'Dunham', label: 'Dunham' },
  //   { value: 'Lavaltrie', label: 'Lavaltrie' },
  //   { value: 'La Prairie', label: 'La Prairie' },
  //   { value: 'Sainte-Julienne', label: 'Sainte-Julienne' },
  //   { value: 'Blue Sea', label: 'Blue Sea' },
  //   { value: "Campbell's Bay", label: "Campbell's Bay" },
  // { value: 'Quebec City', label: 'Quebec City' },
  // { value: 'Saint-Constant', label: 'Saint-Constant' },
  // { value: 'Boisbriand', label: 'Boisbriand' },
  // { value: 'Brébeuf', label: 'Brébeuf' },
  // { value: 'Sainte-Marie-Salomé', label: 'Sainte-Marie-Salomé' },
  // { value: 'Farnham', label: 'Farnham' },
  // {
  //   value: 'Salaberry-de-Valleyfield',
  //   label: 'Salaberry-de-Valleyfield'
  // },
  // { value: 'Senneville', label: 'Senneville' },
  // { value: 'Dorval', label: 'Dorval' },
  // { value: "L'Épiphanie", label: "L'Épiphanie" },
  // { value: 'Rawdon', label: 'Rawdon' },
  // { value: 'Saint-Calixte', label: 'Saint-Calixte' },
  // { value: 'Charlemagne', label: 'Charlemagne' },
  // { value: 'Sainte-Geneviève', label: 'Sainte-Geneviève' },
  // {
  //   value: 'Sainte-Marthe-sur-le-Lac',
  //   label: 'Sainte-Marthe-sur-le-Lac'
  // },
  // { value: 'Sorel-Tracy', label: 'Sorel-Tracy' },
  // { value: 'Rimouski', label: 'Rimouski' },
  // { value: 'Baie-Comeau', label: 'Baie-Comeau' },
  // { value: 'Bromont-Lamothe', label: 'Bromont-Lamothe' },
  // { value: 'Deux-Montagnes', label: 'Deux-Montagnes' },
  // { value: 'Oka', label: 'Oka' },
  // { value: 'Sept-Îles', label: 'Sept-Îles' },
  // { value: 'Hudson', label: 'Hudson' },
  // { value: 'Mont-Tremblant', label: 'Mont-Tremblant' },
  // { value: 'Carignan', label: 'Carignan' },
  // { value: 'Trois-Rivières', label: 'Trois-Rivières' },
  // { value: 'Saint-Lambert', label: 'Saint-Lambert' },
  // { value: 'Dollard-Des Ormeaux', label: 'Dollard-Des Ormeaux' },
  // { value: 'Belcourt', label: 'Belcourt' },
  // {
  //   value: 'Saint-Bruno-de-Montarville',
  //   label: 'Saint-Bruno-de-Montarville'
  // },
  // { value: 'Amqui', label: 'Amqui' },
  // { value: 'Disraeli', label: 'Disraeli' },
  // { value: 'Mascouche', label: 'Mascouche' },
  // { value: 'Repentigny', label: 'Repentigny' },
  // { value: 'Pointe-Claire', label: 'Pointe-Claire' },
  // { value: 'Beauceville', label: 'Beauceville' },
  // { value: 'Cantley', label: 'Cantley' },
  // { value: 'Vaudreuil-Dorion', label: 'Vaudreuil-Dorion' },
  // { value: 'Alma', label: 'Alma' },
  // { value: "Ayer's Cliff", label: "Ayer's Cliff" },
  // { value: 'Beaconsfield', label: 'Beaconsfield' },
  // { value: 'Lachine', label: 'Lachine' },
  // {
  //   value: 'Notre-Dame-de-Montauban',
  //   label: 'Notre-Dame-de-Montauban'
  // },
  // { value: 'Napierville', label: 'Napierville' },
  // { value: 'Val-David', label: 'Val-David' },
  // { value: 'Cap-Saint-Ignace', label: 'Cap-Saint-Ignace' },
  // { value: 'Blainville', label: 'Blainville' },
  // { value: 'Sainte-Marthe', label: 'Sainte-Marthe' },
  // { value: 'Black Lake', label: 'Black Lake' },
  // { value: 'Mont-Saint-Hilaire', label: 'Mont-Saint-Hilaire' },
  // { value: 'Richelieu', label: 'Richelieu' },
  // {
  //   value: 'Sainte-Agathe-des-Monts',
  //   label: 'Sainte-Agathe-des-Monts'
  // },
  // { value: 'Belleterre', label: 'Belleterre' },
  // { value: 'Saint-Georges', label: 'Saint-Georges' },
  // { value: 'Saint-Donat', label: 'Saint-Donat' },
  // { value: 'Bellechasse', label: 'Bellechasse' },
  // { value: 'Calixa-Lavallée', label: 'Calixa-Lavallée' },
  // { value: 'Bonne-Espérance', label: 'Bonne-Espérance' },
  // { value: 'Bécancour', label: 'Bécancour' },
  // { value: 'Rouyn-Noranda', label: 'Rouyn-Noranda' },
  // { value: 'Barkmere', label: 'Barkmere' },
  // { value: 'Chambly', label: 'Chambly' },
  // { value: 'Acton Vale', label: 'Acton Vale' },
  // { value: 'Brownsburg', label: 'Brownsburg' },
  // { value: 'Donnacona', label: 'Donnacona' },
  // { value: 'Boucherville', label: 'Boucherville' },
  // { value: 'Beaulac-Garthby', label: 'Beaulac-Garthby' },
  // {
  //   value: 'Sainte-Marguerite-du-Lac-Masson',
  //   label: 'Sainte-Marguerite-du-Lac-Masson'
  // },
  // {
  //   value: 'Sainte-Lucie-des-Laurentides',
  //   label: 'Sainte-Lucie-des-Laurentides'
  // },
  // { value: 'Bury', label: 'Bury' },
  // { value: 'Cowansville', label: 'Cowansville' },
  // { value: 'Caplan', label: 'Caplan' },
  // { value: 'Saint-Césaire', label: 'Saint-Césaire' },
  // { value: 'Cap-Chat', label: 'Cap-Chat' },
  // {
  //   value: 'Sainte-Thérèse-de-Blainville',
  //   label: 'Sainte-Thérèse-de-Blainville'
  // },
  // { value: 'Sainte-Julie', label: 'Sainte-Julie' },
  // { value: 'Bouchette', label: 'Bouchette' },
  // { value: 'Contrecoeur', label: 'Contrecoeur' },
  // { value: 'Bromont', label: 'Bromont' },
  // { value: 'Beloeil', label: 'Beloeil' },
  // { value: 'Armagh', label: 'Armagh' },
  // { value: "L'Assomption", label: "L'Assomption" },
  // { value: 'Brossard', label: 'Brossard' },
  // { value: 'Hampstead', label: 'Hampstead' },
  // { value: 'Arundel', label: 'Arundel' },
  // { value: "Baie-D'Urfé", label: "Baie-D'Urfé" },
  // { value: 'Châteauguay', label: 'Châteauguay' },
  // { value: 'Berthier-sur-Mer', label: 'Berthier-sur-Mer' },
  // { value: 'Dégelis', label: 'Dégelis' },
  // { value: 'Asbestos', label: 'Asbestos' },
  // { value: 'Beaupré', label: 'Beaupré' },
  // { value: 'Cookshire-Eaton', label: 'Cookshire-Eaton' },
  // { value: 'Montréal-Ouest', label: 'Montréal-Ouest' },
  // { value: "Saint-Adolphe-d'Howard", label: "Saint-Adolphe-d'Howard" },
  // { value: 'Barnston-Ouest', label: 'Barnston-Ouest' },
  // { value: 'LaSalle', label: 'LaSalle' },
  // { value: 'Saint-Jérôme', label: 'Saint-Jérôme' },
  // { value: 'Laval', label: 'Laval' },
  // { value: 'Mirabel', label: 'Mirabel' },
  // { value: 'Bristol', label: 'Bristol' },
  // { value: 'Sainte-Anne-des-Lacs', label: 'Sainte-Anne-des-Lacs' },
  // { value: 'Thetford Mines', label: 'Thetford Mines' },
  // { value: 'Saint-Gabriel', label: 'Saint-Gabriel' },
  // { value: 'Marieville', label: 'Marieville' },
  // { value: 'Candiac', label: 'Candiac' },
  // { value: 'Lévis', label: 'Lévis' },
  // { value: 'Desbiens', label: 'Desbiens' },
  // { value: 'Kirkland', label: 'Kirkland' },
  // { value: 'Saint-Lazare', label: 'Saint-Lazare' },
  // { value: 'Drummondville', label: 'Drummondville' }

  { value: 'Abitibi-Témiscamingue', label: 'Abitibi-Témiscamingue' },
  { value: 'Bas-Saint-Laurent', label: 'Bas-Saint-Laurent' },
  { value: 'Capitale-Nationale', label: 'Capitale-Nationale' },
  { value: 'Centre du Quebec', label: 'Centre du Quebec' },
  { value: 'Chaudière-Appalaches', label: 'Chaudière-Appalaches' },
  { value: 'Cote-nord', label: 'Cote-nord' },
  { value: 'ESTRIE', label: 'ESTRIE' },
  { value: 'Gaspésie/Îles-de-la-Madeleine', label: 'Gaspésie/Îles-de-la-Madeleine' },
  { value: 'Lanaudière', label: 'Lanaudière' },
  { value: 'Laurentides', label: 'Laurentides' },
  { value: 'LAVAL', label: 'LAVAL' },
  { value: 'Mauricie', label: 'Mauricie' },
  { value: 'Montérégie', label: 'Montérégie' },
  { value: 'Montréal', label: 'Montréal' },
  { value: 'Nord-du-Québec', label: 'Nord-du-Québec' },
  { value: 'Outaouais', label: 'Outaouais' },
  { value: 'Saguenay/Lac-Saint-Jean', label: 'Saguenay/Lac-Saint-Jean' },
  ]